import { z } from "zod";

// ENUMS
export enum SessionStatus {
  PENDING = "PENDING",
  CONFIRMED = "CONFIRMED",
  ACTIVE = "ACTIVE",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  NO_SHOW = "NO_SHOW",
}

export enum PlanTier {
  FREE = "FREE",
  PRO = "PRO",
  TEAM = "TEAM",
}

export enum Category {
  CODING = "CODING",
  WRITING = "WRITING",
  STUDYING = "STUDYING",
  DESIGN = "DESIGN",
  ADMIN = "ADMIN",
  OTHER = "OTHER",
}

export enum ReportReason {
  NO_SHOW = "NO_SHOW",
  INAPPROPRIATE = "INAPPROPRIATE",
  HARASSMENT = "HARASSMENT",
  SPAM = "SPAM",
  OTHER = "OTHER",
}

export enum ReportStatus {
  OPEN = "OPEN",
  REVIEWED = "REVIEWED",
  RESOLVED = "RESOLVED",
  DISMISSED = "DISMISSED",
}

// ZOD SCHEMAS

// Sign-up form. The username is generated by the server, so it is not asked for.
export const RegisterInput = z.object({
  email: z.string().email("Invalid email address"),
  password: z
    .string()
    .min(8, "Password must be at least 8 characters")
    .max(128, "Password must be at most 128 characters"),
  displayName: z
    .string()
    .trim()
    .min(2, "Display name must be at least 2 characters")
    .max(50, "Display name must be at most 50 characters"),
});
export type RegisterInput = z.infer<typeof RegisterInput>;

export const LoginInput = z.object({
  email: z.string().email("Invalid email address"),
  password: z.string().min(1, "Password is required"),
});
export type LoginInput = z.infer<typeof LoginInput>;

export const OnboardingInput = z.object({
  timezone: z.string(),
  categories: z
    .array(z.nativeEnum(Category))
    .min(1, "Select at least one category"),
  preferredLength: z
    .array(z.number())
    .min(1, "Select at least one preferred length"),
});
export type OnboardingInput = z.infer<typeof OnboardingInput>;

export const CreateSessionInput = z.object({
  durationMin: z.number().int().positive(),
  scheduledAt: z.string().datetime(),
  category: z.nativeEnum(Category).optional(),
  goal: z.string().optional(),
});
export type CreateSessionInput = z.infer<typeof CreateSessionInput>;

export const CreateReflectionInput = z.object({
  sessionId: z.string().cuid(),
  text: z.string().min(1, "Reflection text is required"),
  rating: z.number().int().min(1).max(5).optional(),
});
export type CreateReflectionInput = z.infer<typeof CreateReflectionInput>;

export const CreateReportInput = z.object({
  reportedId: z.string().cuid(),
  sessionId: z.string().cuid().optional(),
  reason: z.nativeEnum(ReportReason),
  description: z.string().optional(),
});
export type CreateReportInput = z.infer<typeof CreateReportInput>;

// Booking a session (spec §5). The options are soft preferences used when matching.
export const SESSION_DURATIONS = [25, 50, 75] as const;
export const CreateBookingInput = z.object({
  slotTime: z.string().datetime(),
  durationMin: z.union([z.literal(25), z.literal(50), z.literal(75)]),
  cameraOn: z.boolean().default(true),
  quiet: z.boolean().default(false),
  // DESK, WALK ("Moving" in the app) or ANY ("Anything": no preference)
  taskType: z.enum(["DESK", "WALK", "ANY"]).default("ANY"),
  preferFavorites: z.boolean().default(true),
  flexible: z.boolean().default(true),
});
export type CreateBookingInput = z.infer<typeof CreateBookingInput>;

export const CreateFavoriteInput = z.object({
  favoriteId: z.string().cuid(),
});
export type CreateFavoriteInput = z.infer<typeof CreateFavoriteInput>;

export const CreateBlockInput = z.object({
  blockedId: z.string().cuid(),
});
export type CreateBlockInput = z.infer<typeof CreateBlockInput>;

export const UpdateProfileInput = z.object({
  displayName: z.string().min(2).max(50).optional(),
  username: z
    .string()
    .min(3)
    .max(30)
    .regex(/^[a-zA-Z0-9_-]+$/)
    .optional(),
  timezone: z.string().min(1).max(100).optional(),
  hidePhoto: z.boolean().optional(),
  dataSaver: z.boolean().optional(),
});
export type UpdateProfileInput = z.infer<typeof UpdateProfileInput>;

export const UpdatePreferencesInput = z.object({
  googleCalendarSync: z.boolean().optional(),
  emailCalendarInvites: z.boolean().optional(),
  performanceReports: z.boolean().optional(),
  desktopNotifications: z.boolean().optional(),
  quietMode: z.boolean().optional(),
  preferFavorites: z.boolean().optional(),
  timeFormat: z.string().optional(),
  weekStartsOn: z.string().optional(),
  autoRematch: z.boolean().optional(),
  mutedOnJoin: z.boolean().optional(),
  availability: z.string().optional(),
});
export type UpdatePreferencesInput = z.infer<typeof UpdatePreferencesInput>;

// SESSION ROOM (spec §4). The phase is decided by the server, never by the browser.

export const SESSION_PHASES = [
  "UPCOMING",
  "LOBBY",
  "WAITING_FOR_PARTNER",
  "FINDING_REMATCH",
  "SOLO_OFFER",
  "PARTNER_ABSENT",
  "IN_SESSION",
  "EXTENDED",
  "CHECK_OUT",
  "ENDED",
] as const;
export const SessionPhase = z.enum(SESSION_PHASES);
export type SessionPhase = z.infer<typeof SessionPhase>;

export const SessionRoomPerson = z.object({
  id: z.string(),
  displayName: z.string(),
  /** Null when the person hides their photo. */
  avatarUrl: z.string().nullable(),
  quiet: z.boolean(),
  /** In the LiveKit room right now (from webhooks). */
  isPresent: z.boolean(),
});
export type SessionRoomPerson = z.infer<typeof SessionRoomPerson>;

export const SessionRoomResponse = z.object({
  id: z.string(),
  status: z.nativeEnum(SessionStatus),
  phase: SessionPhase,
  isSolo: z.boolean(),
  durationMin: z.number().int(),
  scheduledAt: z.string().datetime(),
  /** When this person's time ends (the booked end, or their own "keep going" end). */
  endsAt: z.string().datetime(),
  joinOpensAt: z.string().datetime(),
  /** The server clock, so the countdown is right even when the device clock is not. */
  serverTime: z.string().datetime(),
  me: SessionRoomPerson.extend({
    goal: z.string().nullable(),
    extensionsLeft: z.number().int(),
  }),
  partner: SessionRoomPerson.nullable(),
  partnerGoal: z.string().nullable(),
  /** Set when the person was paired with someone else; the browser moves to that session. */
  rematchedToSessionId: z.string().nullable(),
  canExtend: z.boolean(),
});
export type SessionRoomResponse = z.infer<typeof SessionRoomResponse>;

export const SessionTokenResponse = z.object({ token: z.string() });
export type SessionTokenResponse = z.infer<typeof SessionTokenResponse>;

export const SetGoalInput = z.object({ goal: z.string().trim().min(1).max(200) });
export type SetGoalInput = z.infer<typeof SetGoalInput>;

export const MAX_SESSION_TASKS = 10;
export const SessionTaskDto = z.object({
  id: z.string(),
  text: z.string(),
  done: z.boolean(),
  position: z.number().int(),
});
export type SessionTaskDto = z.infer<typeof SessionTaskDto>;

export const CreateSessionTaskInput = z.object({ text: z.string().trim().min(1).max(120) });
export type CreateSessionTaskInput = z.infer<typeof CreateSessionTaskInput>;

export const UpdateSessionTaskInput = z
  .object({ text: z.string().trim().min(1).max(120).optional(), done: z.boolean().optional() })
  .refine((value) => value.text !== undefined || value.done !== undefined, {
    message: "Nothing to update",
  });
export type UpdateSessionTaskInput = z.infer<typeof UpdateSessionTaskInput>;

/** One chat line, sent by the reporter's browser. Chat is not stored on the server. */
export const ChatLine = z.object({
  from: z.string().max(100),
  text: z.string().max(500),
  at: z.string().datetime(),
});
export type ChatLine = z.infer<typeof ChatLine>;

export const MAX_REPORT_CHAT_LINES = 50;
export const ReportFromRoomInput = z.object({
  reason: z.nativeEnum(ReportReason),
  description: z.string().max(1000).optional(),
  chat: z.array(ChatLine).max(MAX_REPORT_CHAT_LINES).default([]),
});
export type ReportFromRoomInput = z.infer<typeof ReportFromRoomInput>;

// API RESPONSE WRAPPERS

export interface ApiResponse<T> {
  data?: T;
  message?: string;
}

export interface ApiError {
  error: string;
  statusCode: number;
  details?: any;
}

export interface PaginatedResponse<T> {
  data: T[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}
