import { RegisterInput, LoginInput } from '@focusUp/shared-types';
export declare class AuthService {
    static sendVerificationEmail(userId: string, email: string): Promise<string>;
    static verifyEmail(token: string): Promise<{
        id: string;
        email: string;
        passwordHash: string | null;
        displayName: string;
        username: string;
        avatarUrl: string | null;
        timezone: string;
        categories: import("@prisma/client").$Enums.Category[];
        preferredLength: number[];
        stripeCustomerId: string | null;
        planTier: import("@prisma/client").$Enums.PlanTier;
        strikeCount: number;
        isActive: boolean;
        isBanned: boolean;
        emailVerified: boolean;
        isAdmin: boolean;
        createdAt: Date;
        updatedAt: Date;
    }>;
    static resendVerification(userId: string): Promise<string>;
    static register(data: RegisterInput): Promise<{
        verificationToken: string;
        id: string;
        email: string;
        displayName: string;
        username: string;
        avatarUrl: string | null;
        timezone: string;
        categories: import("@prisma/client").$Enums.Category[];
        preferredLength: number[];
        stripeCustomerId: string | null;
        planTier: import("@prisma/client").$Enums.PlanTier;
        strikeCount: number;
        isActive: boolean;
        isBanned: boolean;
        emailVerified: boolean;
        isAdmin: boolean;
        createdAt: Date;
        updatedAt: Date;
    }>;
    static login(data: LoginInput): Promise<{
        id: string;
        email: string;
        displayName: string;
        username: string;
        avatarUrl: string | null;
        timezone: string;
        categories: import("@prisma/client").$Enums.Category[];
        preferredLength: number[];
        stripeCustomerId: string | null;
        planTier: import("@prisma/client").$Enums.PlanTier;
        strikeCount: number;
        isActive: boolean;
        isBanned: boolean;
        emailVerified: boolean;
        isAdmin: boolean;
        createdAt: Date;
        updatedAt: Date;
    }>;
    static getUserById(id: string): Promise<{
        id: string;
        email: string;
        displayName: string;
        username: string;
        avatarUrl: string | null;
        timezone: string;
        categories: import("@prisma/client").$Enums.Category[];
        preferredLength: number[];
        stripeCustomerId: string | null;
        planTier: import("@prisma/client").$Enums.PlanTier;
        strikeCount: number;
        isActive: boolean;
        isBanned: boolean;
        emailVerified: boolean;
        isAdmin: boolean;
        createdAt: Date;
        updatedAt: Date;
    } | null>;
}
